// customer authentication types
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";


// auction types controller
export const CREATE_AUCTION_REQUEST = "CREATE_AUCTION_REQUEST";
export const CREATE_AUCTION_SUCCESS = "CREATE_AUCTION_SUCCESS";
export const CREATE_AUCTION_FAILED = "CREATE_AUCTION_FAILED";

export const GET_AUCTION_REQUEST = "GET_AUCTION_REQUEST";
export const GET_AUCTION_SUCCESS = "GET_AUCTION_SUCCESS";
export const GET_AUCTION_FAILED = "GET_AUCTION_FAILED";

export const GET_SINGLE_AUCTION_REQUEST = "GET_SINGLE_AUCTION_REQUEST";
export const GET_SINGLE_AUCTION_SUCCESS = "GET_SINGLE_AUCTION_SUCCESS";
export const GET_SINGLE_AUCTION_FAILED = "GET_SINGLE_AUCTION_FAILED";

export const DELETE_AUCTION_REQUEST = "DELETE_AUCTION_REQUEST";
export const DELETE_AUCTION_SUCCESS = "DELETE_AUCTION_SUCCESS";
export const DELETE_AUCTION_FAILED = "DELETE_AUCTION_FAILED";

// bid types controller
export const CREATE_BID_REQUEST = "CREATE_BID_REQUEST";
export const CREATE_BID_SUCCESS = "CREATE_BID_SUCCESS";
export const CREATE_BID_FAILED = "CREATE_BID_FAILED";

export const GET_BID_REQUEST = "GET_BID_REQUEST";
export const GET_BID_SUCCESS = "GET_BID_SUCCESS";
export const GET_BID_FAILED = "GET_BID_FAILED";